
DROP TABLE PACIENTE CASCADE CONSTRAINTS;
DROP TABLE TRIAGEM CASCADE CONSTRAINTS;
DROP TABLE DIAGNOSTICO CASCADE CONSTRAINTS;
DROP TABLE USUARIO CASCADE CONSTRAINTS;

CREATE TABLE USUARIO (
    id NUMBER(19, 0) CONSTRAINT PK_ID_USUARIO PRIMARY KEY,
    CPF VARCHAR2(14 CHAR) CONSTRAINT USUARIO_CPF_NN NOT NULL,
    CARGO VARCHAR2(20 CHAR) CONSTRAINT USUARIO_CARGO_NN NOT NULL,
    EMAIL VARCHAR2(30 CHAR) CONSTRAINT USUARIO_EMAIL_NN NOT NULL,
    SENHA VARCHAR2(40 CHAR) CONSTRAINT USUARIO_SENHA_NN NOT NULL,
    NOME VARCHAR2(100 CHAR) CONSTRAINT USUARIO_NOME_NN NOT NULL
);

CREATE TABLE DIAGNOSTICO (
    id NUMBER(19, 0) CONSTRAINT PK_ID_DIAGNOSTICO PRIMARY KEY,
    DATA_HORA_DIAGNOSTICO TIMESTAMP(6) CONSTRAINT DIAG_DATA_HORA_NN NOT NULL,
    PROVAVEL_COVID NUMBER(1, 0) CONSTRAINT DIAG_PROVAVEL_COVID_NN NOT NULL
);

CREATE TABLE PACIENTE (
    id NUMBER(19, 0) CONSTRAINT PK_ID_PACIENTE PRIMARY KEY,
    DATA_NASC DATE CONSTRAINT PACIENTE_DATA_NASC_NN NOT NULL,
    SEXO NUMBER(3, 0) CONSTRAINT PACIENTE_SEXO_NN NOT NULL,
    CELULAR VARCHAR2(14 CHAR) CONSTRAINT PACIENTE_CELULAR_NN NOT NULL,
    CPF VARCHAR2(14 CHAR) CONSTRAINT PACIENTE_CPF_NN NOT NULL,
    EMAIL VARCHAR2(30 CHAR) CONSTRAINT PACIENTE_EMAIL_NN NOT NULL,
    NOME VARCHAR2(100 CHAR) CONSTRAINT PACIENTE_NOME_NN NOT NULL,
    registrouPaciente_id NUMBER(19, 0) CONSTRAINT FK_REGISTROU_PACIENTE REFERENCES USUARIO(id)
);

CREATE TABLE TRIAGEM (
    id NUMBER(19, 0) CONSTRAINT PK_ID_TRIAGEM PRIMARY KEY,
    DATA_TRIAGEM DATE CONSTRAINT TRIAGEM_DATA_TRIAGEM_NN NOT NULL,
    ASMA NUMBER(1, 0) CONSTRAINT TRIAGEM_ASMA_NN NOT NULL,
    CONTATO_INFECTADO NUMBER(1, 0) CONSTRAINT TRIAGEM_CONTATO_INF_NN NOT NULL,
    CORIZA NUMBER(1, 0) CONSTRAINT TRIAGEM_CORIZA_NN NOT NULL,
    DIABETES NUMBER(1, 0) CONSTRAINT TRIAGEM_DIABETES_NN NOT NULL,
    DOENCA_CARDIACA NUMBER(1, 0) CONSTRAINT TRIAGEM_DOENCA_CARD_NN NOT NULL,
    DOENCA_PULMONAR_CRONICA NUMBER(1, 0) CONSTRAINT TRIAGEM_DOENCA_PULM_NN NOT NULL,
    DOR_CABECAC NUMBER(1, 0) CONSTRAINT TRIAGEM_DOR_CABECA_NN NOT NULL,
    DOR_GARGANTA NUMBER(1, 0) CONSTRAINT TRIAGEM_DOR_GARGANTA_NN NOT NULL,
    FADIGA NUMBER(1, 0) CONSTRAINT TRIAGEM_FADIGA_NN NOT NULL,
    FAMILIAR_LOCAL_PUBLICO NUMBER(1, 0) CONSTRAINT TRIAGEM_FAM_LOC_PUB_NN NOT NULL,
    FEBRE NUMBER(1, 0) CONSTRAINT TRIAGEM_FEBRE_NN NOT NULL,
    HIPERTENSAO NUMBER(1, 0) CONSTRAINT TRIAGEM_HIPERTENSAO_NN NOT NULL,
    LOCAL_PUBLICO NUMBER(1, 0) CONSTRAINT TRIAGEM_LOCAL_PUB_NN NOT NULL,
    MULIDAO NUMBER(1, 0) CONSTRAINT TRIAGEM_MULIDAO_NN NOT NULL,
    PROBLEMAS_GASTRO NUMBER(1, 0) CONSTRAINT TRIAGEM_PROB_GASTRO_NN NOT NULL,
    PROBLEMA_RESPIRATORIO NUMBER(1, 0) CONSTRAINT TRIAGEM_PROB_RESP_NN NOT NULL,
    TOSSE_SECA NUMBER(1, 0) CONSTRAINT TRIAGEM_TOSSE_SECA_NN NOT NULL,
    VIAGEM_EXTERIOR NUMBER(1, 0) CONSTRAINT TRIAGEM_VIAGEM_EXT_NN NOT NULL,
    diagnostico_id NUMBER(19, 0) CONSTRAINT FK_DIAGNOSTICO REFERENCES DIAGNOSTICO(id),
    paciente_id NUMBER(19, 0) CONSTRAINT FK_PACIENTE REFERENCES PACIENTE(id),
    registrouTriagem_id NUMBER(19, 0) CONSTRAINT FK_REGISTROU_TRIAGEM REFERENCES USUARIO(id)
);


