-- O banco de dados Oracle da FIAP estava indisponível.
-- Então foi utilizado o MySQL para criar as tabelas para a demonstração em vídeo.

CREATE DATABASE IF NOT EXISTS predmed;
USE predmed;

CREATE TABLE IF NOT EXISTS USUARIO (
    id BIGINT PRIMARY KEY DEFAULT 1 DEFAULT 1,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    SENHA VARCHAR(40) NOT NULL,
    CARGO VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS PACIENTE (
    id BIGINT PRIMARY KEY DEFAULT 1,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(14),
    EMAIL VARCHAR(30),
    CELULAR VARCHAR(14),
    SEXO CHAR(1) NOT NULL,
    DATA_NASC DATE NOT NULL,
    registrouPaciente_id BIGINT,
    FOREIGN KEY (registrouPaciente_id) REFERENCES USUARIO(id)
);

CREATE TABLE IF NOT EXISTS DIAGNOSTICO (
    id BIGINT PRIMARY KEY DEFAULT 1,
    PROVAVEL_COVID BOOLEAN NOT NULL,
    DATA_HORA_DIAGNOSTICO TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS TRIAGEM (
    id BIGINT PRIMARY KEY DEFAULT 1,
    DATA_TRIAGEM DATE NOT NULL,
    paciente_id BIGINT,
    registrouTriagem_id BIGINT,
    diagnostico_id BIGINT,
    PROBLEMA_RESPIRATORIO BOOLEAN NOT NULL,
    FEBRE BOOLEAN,
    TOSSE_SECA BOOLEAN,
    DOR_GARGANTA BOOLEAN,
    CORIZA BOOLEAN,
    ASMA BOOLEAN,
    DOENCA_PULMONAR_CRONICA BOOLEAN,
    DOR_CABECAC BOOLEAN,
    DOENCA_CARDIACA BOOLEAN,
    DIABETES BOOLEAN,
    HIPERTENSAO BOOLEAN,
    FADIGA BOOLEAN,
    PROBLEMAS_GASTRO BOOLEAN,
    VIAGEM_EXTERIOR BOOLEAN,
    CONTATO_INFECTADO BOOLEAN,
    MULIDAO BOOLEAN,
    LOCAL_PUBLICO BOOLEAN,
    FAMILIAR_LOCAL_PUBLICO BOOLEAN,
    FOREIGN KEY (paciente_id) REFERENCES PACIENTE(id),
    FOREIGN KEY (registrouTriagem_id) REFERENCES USUARIO(id),
    FOREIGN KEY (diagnostico_id) REFERENCES DIAGNOSTICO(id)
);
